### ISSUE TITLE
Protege 5 Beta 17 - queries won't execute with NoHR 2.0 - Java 8

### ISSUE THREAD

**Issue by dockstreet** [NoHRReasoner/NoHR#5]
Hi,

I've been able to get the cities.owl ontology to work fine with Protege 4.3 ; but when I try to query "seasideCity(X)"  (without the period now? )

I get no results? Is there a way to turn on additional debugging? It seems to be broken, but I'm not sure as the NoHR rules now have to be entered 1 by 1 instead of freeform?

starting NoHR
                        1  ontology reduction [21:59:12]
checking axioms support
                                ontology classification [21:59:12]
                                0.153 s
                        0.154 s
                        1  ontology processing [21:59:12]
checking axioms support
                                ontology classification [21:59:12]
                                0.008 s
                                ontology translation [21:59:12]
                                0.005 s
                        0.019 s
                        1  rules parsing [21:59:12]
                        0.001 s
                        1  rules parsing [22:0:27]
                        0.004 s
                        1  query [22:0:27]
                        querying: q():-seasideCity(X)
                                file writing [22:0:27]
                                0.002 s
                                xsb loading [22:0:27]
                                0.017 s
                        0.225 s

**Comment by matthiasknorr** [comment]
Hi dockstreet,

Assuming that you are using Protégé 5 (the message body seems to indicate the contrary, so if this is the problem, please note that NoHR 2.0 is designed for Protégé 5), I uploaded  the cities example to our repository:

https://github.com/NoHRReasoner/NoHR-examples/tree/master/Cities

To run queries, please use the following syntax in NoHR 2.0:

seasideCity(?X)

The additional question mark was introduced to ensure that variables cannot be mixed up with individual names in the ontology beginning with a capital letter.

For me it works just fine, please let me know if the problem persists using the uploaded owl and rule file.

Best,
Matthias Knorr

**Comment by dockstreet** [comment]
Hi Mathias,

I didn't have the new syntax down correctly works just fine now  
Adding the "?" did the trick!

seasideCity(?X)

Thanks!
