### ISSUE TITLE
Adding DataPropertyRange - results in Unsupported Axiom

### ISSUE THREAD

**Issue by dockstreet** [NoHRReasoner/NoHR#6]
Hi,

I was able to add a DataProperty and DataPropertyAssertion without issue. 

Declaration(DataProperty(<http://www.semanticweb.org/ontologies/2013/4/cities.owl#hasPopulation>))

DataPropertyAssertion(<http://www.semanticweb.org/ontologies/2013/4/cities.owl#hasPopulation> <http://www.semanticweb.org/ontologies/2013/4/cities.owl#lisbon> "530847"^^xsd:long)

But when I added  a DataPropertyRange - like the below , I got an error saying "The active ontology contains some unsupported axioms"

unsupported axioms [DataPropertyRange(<http://www.semanticweb.org/ontologies/2013/4/cities.owl#hasPopulation> xsd:long)]

data property range added:
DataPropertyRange(<http://www.semanticweb.org/ontologies/2013/4/cities.owl#hasPopulation> xsd:long)

modified cities.owl (sorry couldn't attach a file)

Prefix(owl:=<http://www.w3.org/2002/07/owl#>)
Prefix(rdf:=<http://www.w3.org/1999/02/22-rdf-syntax-ns#>)
Prefix(xml:=<http://www.w3.org/XML/1998/namespace>)
Prefix(xsd:=<http://www.w3.org/2001/XMLSchema#>)
Prefix(rdfs:=<http://www.w3.org/2000/01/rdf-schema#>)

Ontology(<http://www.semanticweb.org/ontologies/2013/4/cities.owl>

Declaration(Class(<http://www.semanticweb.org/ontologies/2013/4/cities.owl#beach>))
Declaration(Class(<http://www.semanticweb.org/ontologies/2013/4/cities.owl#nonSeasideCity>))
Declaration(Class(<http://www.semanticweb.org/ontologies/2013/4/cities.owl#portCity>))
Declaration(Class(<http://www.semanticweb.org/ontologies/2013/4/cities.owl#rainyCity>))
Declaration(Class(<http://www.semanticweb.org/ontologies/2013/4/cities.owl#recreational>))
Declaration(Class(<http://www.semanticweb.org/ontologies/2013/4/cities.owl#recreationalCity>))
Declaration(Class(<http://www.semanticweb.org/ontologies/2013/4/cities.owl#seasideCity>))
Declaration(ObjectProperty(<http://www.semanticweb.org/ontologies/2013/4/cities.owl#has>))
Declaration(ObjectProperty(<http://www.semanticweb.org/ontologies/2013/4/cities.owl#onSea>))
Declaration(DataProperty(<http://www.semanticweb.org/ontologies/2013/4/cities.owl#hasPopulation>))
Declaration(NamedIndividual(<http://www.semanticweb.org/ontologies/2013/4/cities.owl#aquaticsCentre>))
Declaration(NamedIndividual(<http://www.semanticweb.org/ontologies/2013/4/cities.owl#atlanticOcean>))
Declaration(NamedIndividual(<http://www.semanticweb.org/ontologies/2013/4/cities.owl#barcelona>))
Declaration(NamedIndividual(<http://www.semanticweb.org/ontologies/2013/4/cities.owl#hamburg>))
Declaration(NamedIndividual(<http://www.semanticweb.org/ontologies/2013/4/cities.owl#lisbon>))
Declaration(NamedIndividual(<http://www.semanticweb.org/ontologies/2013/4/cities.owl#manchester>))
Declaration(NamedIndividual(<http://www.semanticweb.org/ontologies/2013/4/cities.owl#mediterranean>))
Declaration(NamedIndividual(<http://www.semanticweb.org/ontologies/2013/4/cities.owl#sydney>))
Declaration(NamedIndividual(<http://www.semanticweb.org/ontologies/2013/4/cities.owl#tasmanSea>))
SubClassOf(<http://www.semanticweb.org/ontologies/2013/4/cities.owl#beach> <http://www.semanticweb.org/ontologies/2013/4/cities.owl#recreational>)
SubClassOf(<http://www.semanticweb.org/ontologies/2013/4/cities.owl#nonSeasideCity> owl:Thing)
SubClassOf(<http://www.semanticweb.org/ontologies/2013/4/cities.owl#portCity> owl:Thing)
SubClassOf(<http://www.semanticweb.org/ontologies/2013/4/cities.owl#rainyCity> owl:Thing)
SubClassOf(<http://www.semanticweb.org/ontologies/2013/4/cities.owl#recreational> owl:Thing)
SubClassOf(<http://www.semanticweb.org/ontologies/2013/4/cities.owl#recreationalCity> owl:Thing)
SubClassOf(<http://www.semanticweb.org/ontologies/2013/4/cities.owl#seasideCity> <http://www.semanticweb.org/ontologies/2013/4/cities.owl#recreationalCity>)
SubClassOf(<http://www.semanticweb.org/ontologies/2013/4/cities.owl#seasideCity> ObjectSomeValuesFrom(<http://www.semanticweb.org/ontologies/2013/4/cities.owl#has> <http://www.semanticweb.org/ontologies/2013/4/cities.owl#beach>))
DataPropertyRange(<http://www.semanticweb.org/ontologies/2013/4/cities.owl#hasPopulation> xsd:long)
ClassAssertion(<http://www.semanticweb.org/ontologies/2013/4/cities.owl#recreational> <http://www.semanticweb.org/ontologies/2013/4/cities.owl#aquaticsCentre>)
ClassAssertion(<http://www.semanticweb.org/ontologies/2013/4/cities.owl#portCity> <http://www.semanticweb.org/ontologies/2013/4/cities.owl#barcelona>)
ObjectPropertyAssertion(<http://www.semanticweb.org/ontologies/2013/4/cities.owl#onSea> <http://www.semanticweb.org/ontologies/2013/4/cities.owl#barcelona> <http://www.semanticweb.org/ontologies/2013/4/cities.owl#mediterranean>)
ClassAssertion(<http://www.semanticweb.org/ontologies/2013/4/cities.owl#nonSeasideCity> <http://www.semanticweb.org/ontologies/2013/4/cities.owl#hamburg>)
ClassAssertion(<http://www.semanticweb.org/ontologies/2013/4/cities.owl#portCity> <http://www.semanticweb.org/ontologies/2013/4/cities.owl#hamburg>)
ClassAssertion(<http://www.semanticweb.org/ontologies/2013/4/cities.owl#portCity> <http://www.semanticweb.org/ontologies/2013/4/cities.owl#lisbon>)
ObjectPropertyAssertion(<http://www.semanticweb.org/ontologies/2013/4/cities.owl#onSea> <http://www.semanticweb.org/ontologies/2013/4/cities.owl#lisbon> <http://www.semanticweb.org/ontologies/2013/4/cities.owl#atlanticOcean>)
DataPropertyAssertion(<http://www.semanticweb.org/ontologies/2013/4/cities.owl#hasPopulation> <http://www.semanticweb.org/ontologies/2013/4/cities.owl#lisbon> "530847"^^xsd:long)
ClassAssertion(<http://www.semanticweb.org/ontologies/2013/4/cities.owl#rainyCity> <http://www.semanticweb.org/ontologies/2013/4/cities.owl#manchester>)
ObjectPropertyAssertion(<http://www.semanticweb.org/ontologies/2013/4/cities.owl#has> <http://www.semanticweb.org/ontologies/2013/4/cities.owl#manchester> <http://www.semanticweb.org/ontologies/2013/4/cities.owl#aquaticsCentre>)
ClassAssertion(<http://www.semanticweb.org/ontologies/2013/4/cities.owl#portCity> <http://www.semanticweb.org/ontologies/2013/4/cities.owl#sydney>)
ObjectPropertyAssertion(<http://www.semanticweb.org/ontologies/2013/4/cities.owl#onSea> <http://www.semanticweb.org/ontologies/2013/4/cities.owl#sydney> <http://www.semanticweb.org/ontologies/2013/4/cities.owl#tasmanSea>)
SubClassOf(ObjectSomeValuesFrom(<http://www.semanticweb.org/ontologies/2013/4/cities.owl#has> <http://www.semanticweb.org/ontologies/2013/4/cities.owl#recreational>) <http://www.semanticweb.org/ontologies/2013/4/cities.owl#recreationalCity>)
)

**Comment by matthiasknorr** [comment]
Hi dockstreet,

That is all correct for the current version and stems primarily from the fact that the EL reasoner ELK used for classification does not support these axioms. (This can be checked, e.g., by downloading the ELK plug-in from [here](https://code.google.com/p/elk-reasoner/) and trying to use ELK to classify this ontology.) Hence, such axioms were/are of low priority for us.

Of course, we are always willing to try to accommodate user's requests. For this purpose, could you briefly point out the desired behaviour/added value from admitting data property ranges on this example (or another)?

**Comment by dockstreet** [comment]
Hi Matthias,

Thanks for explaining. 

I was going to try to use the range for data validation to make sure that an "hasPopulation" assertion had a data type of xsd:long. Is that uncommon or is there a better way to do that with ELKs' axiom support?

**Comment by matthiasknorr** [comment]
Hi dockstreet,

That makes certainly sense and is in fact the most likely usage of the data property ranges that are admitted in the [OWL EL profile](http://www.w3.org/TR/owl2-profiles/#OWL_2_EL) in general.

Unfortunately, ELK does not support this and to the best of my knowledge there is no way around it. This simply means that these axioms are ignored and the desired check is not done.

For the ontology alone, this can be circumvented by using a different OWL reasoner. But our rule translation does not handle this, so you would not be able to check assertions in the rules currently anyway.

What we can do though in the next version is change the current behaviour of blocking the reasoning process into one where a warning is issued after which the system proceeds anyway. This at least would allow handling ontologies with such axioms even if they are ignored for NoHR itself.

Best Regards,
Matthias Knorr

**Comment by dockstreet** [comment]
Thanks Matthias, much appreciated !!!!
