### ISSUE TITLE
Using NoHR in Java 

### ISSUE THREAD

**Issue by hmqq** [NoHRReasoner/NoHR#9]
Hi,

I want to use NoHR in java program, where i need to pass ontology file and rule file to NoHR and then query the hybrid KB. I am not sure how to use NoHR in java because i haven't find any documentation mentioning the usage in java programs. Could you kindly tell me how can i use NoHR in my program.

Thanks.

**Comment by matthiasknorr** [comment]
Hi,

Please have a look in the benchmark part where tests are run on the command line (which can be used to check how the calls you want to perform can be done). You can also check the current branch on db connection where such test involves data access via ODBC.

I hope this helps.

**Comment by hmqq** [comment]
I have modified one of the file in benchmark part to pass my files and execute queries. I am using this code in eclipse.
public class testing {
	
	static File ont = new File("C:\\Users\\user\\Desktop\\Bird.owl");
	static String rules = "C:\\Users\\user\\Desktop\\rules.p";
	static String query = "C:\\Users\\user\\Desktop\\queries.txt";
	
    public static void main(String[] args) throws OWLOntologyCreationException, OWLOntologyStorageException,
            OWLProfilesViolationsException, IOException, CloneNotSupportedException, UnsupportedAxiomsException,
            IPException, PrologEngineCreationException, ParseException, Exception {
    	
    	   final QueryConfigParser queriesParser = new QueryConfigParser();
    	   final Path queriesFile = FileSystems.getDefault().getPath(query).toAbsolutePath();
           Vector<?> queries = null;
           try {
               queries = queriesParser.createQueryList(queriesFile.toString());
           } catch (final Exception e) {
               e.printStackTrace();
           }
    	   
    	   OWLOntologyManager om = OWLManager.createOWLOntologyManager();
    	   OWLOntology ontology = om.loadOntologyFromOntologyDocument(ont);
           
    	   NoHRHybridKBConfiguration configuration = new NoHRHybridKBConfiguration();
    	   System.out.println(" check1");
    	   
    	   final HybridKB nohr = new NoHRHybridKB(configuration, ontology, Model.program());
           final NoHRParser parser = new NoHRRecursiveDescentParser(nohr.getVocabulary());
           final ProgramPersistenceManager programPersistenceManager = new ProgramPersistenceManager(nohr.getVocabulary());
           
           final Iterator<?> queriesIt1 = queries.iterator();
           while (queriesIt1.hasNext()) {
               final QuerySpecification querySpecification = (QuerySpecification) queriesIt1.next();
               try {
                   final Collection<Answer> ans = nohr
                           .allAnswers(parser.parseQuery(querySpecification.query_.getString()));
                   System.out.println(ans.size() + " answers");
               } catch (final Exception e) {
                   e.printStackTrace();
               }
           }
           
           final Path progsDir = FileSystems.getDefault().getPath(rules).toAbsolutePath();
           final List<Path> files = new ArrayList<Path>();
           final DirectoryStream<Path> progsStream = Files.newDirectoryStream(progsDir);
           for (final Path p : progsStream) {
               files.add(p);
           }
           
           for (final Path progFile : files) {
               RuntimesLogger.setDataset(ont.getName().toString()+ "+" + progFile.getFileName().toString().replaceFirst(".p", ""));
               try {
            	   System.out.println("rules parsing");
                   final Program program = programPersistenceManager.read(progFile.toFile());
                   System.out.println("rules loading");
                   nohr.getProgram().addAll(program);
               } catch (final PrologParserException e) {
                   System.err.println("syntax error at line " + e.getLineNumber() + "column " + e.getStringPosition());
               }
               
               
               queries.iterator();
               for (int i = 0; i < queries.size(); i++) {
                   final QuerySpecification querySpecification = (QuerySpecification) queries.get(i);
                   final Collection<Answer> ans = nohr
                           .allAnswers(parser.parseQuery(querySpecification.query_.getString()));
                     System.out.println(ans.size() + " answers");
               }
               nohr.getProgram().clear();
           }
           progsStream.close();

       } 
           
  }
 i get the following error.
Exception in thread "main" java.lang.NullPointerException
	at java.io.File.<init>(File.java:277)
	at pt.unl.fct.di.novalincs.nohr.hybridkb.NoHRHybridKBConfiguration.<init>(NoHRHybridKBConfiguration.java:13)
	at benchmark.testing.main(testing.java:64)

I think its related to configuration of NoHRHybridKB, i don't know how to configure it. Also i am not sure whether the above code is the right way to do what i want. Kindly help me.

**Comment by matthiasknorr** [comment]
Hi,

It is difficult to do ad-hoc debugging from distance; still
1) you may try to run the original tests "as is", and then try mixing in your data/files;
2) you can also have a look at the nohr-benchmark-leightweight folder in the db-connection-test branch;
3) there, for example, in file benchmark.java, you can find a configuration definition example.

**Comment by hmqq** [comment]
> Hi,
> 
> It is difficult to do ad-hoc debugging from distance; still
> 
> 1. you may try to run the original tests "as is", and then try mixing in your data/files;
> 2. you can also have a look at the nohr-benchmark-leightweight folder in the db-connection-test branch;
> 3. there, for example, in file benchmark.java, you can find a configuration definition example.

i cannot see db-connection-test branch or nohr-benchmark-leightweight folder or benchmark.java .  where are these folders/files.

**Comment by matthiasknorr** [comment]
You can see a box more in the left upper area labelled with master. You can click on that and switch to a different branch.

**Comment by hmqq** [comment]
Okay I have looked at nohr-benchmark-leightweight folder and then modify it according to my need. And I'm still getting null exception.
SEVERE: Loading Error
java.lang.NullPointerException
	at owl.cs.SPARQLinng.NoHRTest.<init>(NoHRTest.java:39)
	at owl.cs.SPARQLinng.Loading.<init>(Loading.java:23)
	at owl.cs.SPARQLinng.Loading.main(Loading.java:62)

pt.unl.fct.di.novalincs.nohr.hybridkb.NoHRHybridKB.NoHRHybridKB(File binDirectory, OWLOntology ontology, Program program, Vocabulary vocabulary, Profile profile) 
what do we need to give in File binDirectory?

**Comment by hmqq** [comment]
I am getting exception on this Line: 
NoHRHybridKB kb = new NoHRHybridKB(new File(NOHR_XSB_DIRECTORY), ontology, program, vocabulary, null);

Exception in thread "main" java.lang.NoSuchMethodError: pt.unl.fct.di.novalincs.nohr.hybridkb.NoHRHybridKB.<init>(Ljava/io/File;Lorg/semanticweb/owlapi/model/OWLOntology;Lpt/unl/fct/di/novalincs/nohr/model/Program;Lpt/unl/fct/di/novalincs/nohr/model/vocabulary/Vocabulary;Lpt/unl/fct/di/novalincs/nohr/translation/Profile;)V
	at owl.cs.NoHRKB.HybridKB.QueryRun(HybridKB.java:87)
	at owl.cs.NoHRKB.HybridKB.main(HybridKB.java:72)
